### ISSUE TITLE
Kelner może odznaczać elementy zamówienia

### ISSUE THREAD

**Issue by karczewskip** [karczewskip/Waiter-Management-2#27]
Kelner na panelu ma możliwość oznaczenia elementu zamówienia jako dostarczone. Stół powinien dostawać aktualny komunikat o zmianie stanu zamówienia.

**Comment by ILoveCamelCasing** [comment]
Dodałem funkcjonalność. Należy przeprowadzić migrację bazy danych (do tabeli MenuItemQuantities dodałem pole Ready).
