### ISSUE TITLE
Stół może wezwać kelnera.

### ISSUE THREAD

**Issue by karczewskip** [karczewskip/Waiter-Management-2#30]
Stół powinien mieć możliwość wezwania kelnera. Kiedy zamówienie nie zostało złożone to wybierany powinien być dowolny kelner jeżeli zamówienie jest w trakcie to powiadomienie powinien dostawać aktualny kelner.

**Comment by ILoveCamelCasing** [comment]
Dodałem już możliwość wołania kelnera (u kelnera pojawia się stosowny komunikat), jednak (przynajmniej u mnie), widok OrdersView jest zawsze pusty, przez co szwankuje znajdowanie kelnera, co się kończy tym, że wzywani są wszyscy aktywni kelnerzy.
